### ISSUE TITLE
Compilation error with gcc 4.6.1

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#102]
Compilation error with gcc 4.6.1 

~~~
[  0%] Building C object src/C-interface/dense/CMakeFiles/bml-dense-single_real.dir/bml_normalize_dense_typed.c.o
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c: In function ‘bml_gershgorin_dense_single_real’:
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:76: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, or ‘||’ before ‘max’
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:77: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, or ‘||’ before ‘min’
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:101: error: ‘emax’ not specified in enclosing parallel
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:71: error: enclosing parallel
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:103: error: ‘emin’ not specified in enclosing parallel
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:71: error: enclosing parallel
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c: In function ‘bml_gershgorin_partial_dense_single_real’:
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:149: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, or ‘||’ before ‘max’
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:150: error: expected ‘+’, ‘*’, ‘-’, ‘&’, ‘^’, ‘|’, ‘&&’, or ‘||’ before ‘min’
/turquoise/users/cnegre/bml/src/C-interface/dense/bml_normalize_dense_typed.c:165: error: ‘emax’ not specified in enclosing parallel
~~~

**Comment by nicolasbock** [comment]
The reason for this error is that the `max` and `min` reductions were introduced with the OpenMP 3.1 standard which was not supported by gcc until their 4.7 release. In other words, the compiler you are using does not support this feature. I'll have a look whether we can remove those reduction in favor of something that is supported.

**Comment by nicolasbock** [comment]
I found a replacement algorithm we could use. I'll replace all min/max reductions in the code. See #103.

**Comment by suemni** [comment]
Is there a reason we should care about the <gcc-4.7 compilers?
We have limited people resources to work on this and our focus is on current and new architectures.
I would not replace the OpenMP reductions unless the performance is the same.
If you must support old compilers, please supply the min/max code with ifdefs.

**Comment by nicolasbock** [comment]
@cnegre What system did you build the bml on? What I am specifically asking is why you were using such an old gcc. I am sure you had a good reason, I am just wondering :smile:.

**Comment by nicolasbock** [comment]
I'll close this. We decided that we won't support `<gcc-4.7` and require `>=OpenMP-3.1`.
