### ISSUE TITLE
Progress library not compiling with the newest version of bml

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#134]
The last version of progress compiles well with: 
git checkout afe5c463ef1d2643476dda8082132707054e2f47
but not with the very last one

**Comment by nicolasbock** [comment]
I pushed https://github.com/lanl/qmd-progress/pull/84 which should address this issue.

**Comment by nicolasbock** [comment]
@cnegre Do you still see issues here or can we close this?

**Comment by cnegre** [comment]
No. We can close it

**Comment by nicolasbock** [comment]
Thanks!
