### ISSUE TITLE
Compilation without omp

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#144]
When BML_OMP is set to no the compilation fails cause omp.h is still included in 
the source code and not protected with "ifdefs"

**Comment by suve** [comment]
Hi. I took a quick look at the code (`master` branch) and the only place I've found where `#include <omp.h>` isn't guarded by IFDEF is `src/C-interface/bml_allocate.c`. In all the other files the include is guarded, albeit by the `_OPENMP` symbol, not `BML_OMP`. (By the way, did you mean `BML_OPENMP`? The shorter `BML_OMP` doesn't appear anywhere within the project.)

**Comment by nicolasbock** [comment]
Hi @suve, thanks for looking into this! You are right, that's the only place I found as well. It would be great if you could send us a pull request with a fix!

To explain further, in https://github.com/lanl/bml/blob/master/CMakeLists.txt#L113 you'll find that we use `BML_OPENMP` as a switch to `CMake` to indicate that the user would like to enable `OpenMP`. If `CMake` finds a working `OpenMP` implementation, in particular, if `>= OpenMP-3.1`, then `OpenMP` is enabled causing the compiler to define `_OPENMP` which we use to guard the `#include <omp.h>`. Of course if the compiler does not support `OpenMP` then the code should not `#include <omp.h>`.

Thanks!

**Comment by nicolasbock** [comment]
This is closed with #149
