### ISSUE TITLE
readlink in mac

### ISSUE THREAD

**Issue by enriquemasa** [lanl/bml#171]
Hi,

I am trying to install the BML library on a OS X 10.12.6 and the readlink command in build.sh gives an error.

Thanks,
Enrique

**Comment by nicolasbock** [comment]
I am looking into it. Thanks for reporting!

**Comment by fyrazu** [comment]
Hi,

Same issue here with OS X 10.13.3. I was wondering if there have been any updates? 

Thank you,

Fernando

**Comment by nicolasbock** [comment]
@enriquemasa is this still an issue with the latest version of the library?
