### ISSUE TITLE
Overhead for small dense matrix-matrix multiplications

### ISSUE THREAD

**Issue by AndersNiklasson** [lanl/bml#192]
Running example3, which compares the bml wrapper for dense matrix multiplications with a direct call to dgemm, we find a significant overhead for smaller matrices. For example, using a 250x250 matrix, we find that bml takes about 15 ms, vs only 2 ms for standalone dgemm. For a 2500x2500 matrix the timings are almost the same, i.e. 253 ms vs. 250 ms.

**Comment by nicolasbock** [comment]
2 ms is rather small. Have you tried to put a loop around the MM and then print the time per iteration? The relative error in the time measurement might be quite large.
