### ISSUE TITLE
failure with ./tests/bml-test --testname multiply_x2 --precision single_real --N 40 --M 40

### ISSUE THREAD

**Issue by tokshgithub** [lanl/bml#237]
**Describe the bug**
running bml with:
./tests/bml-test --testname multiply_x2 --precision single_real --N 40 --M 40
fails, while 
./tests/bml-test --testname multiply_x2 --precision double_real --N 40 --M 40
passes

**Comment by nicolasbock** [comment]
I'll have a look.

**Comment by tokshgithub** [comment]
> I'll have a look.

sounds good! if it does not fail the first time, it will fail on the second. i have not looked into it but i believe it might be your tolerance variable. should be double real when required precision is double real, that idea should follow for al other degree of precision, respectively.

**Comment by nicolasbock** [comment]
Hi @tokshgithub !

Is this still an issue?
