### ISSUE TITLE
purpose of line of code

### ISSUE THREAD

**Issue by tokshgithub** [lanl/bml#240]
What is the purpose of this line of code:
Are you trying to allocated host array to be copied to gpu when you use magma?

#ifdef BML_USE_MAGMA
    REAL_T *B_matrix = bml_allocate_memory(sizeof(REAL_T) * B->N * B->N);
#else
    REAL_T *B_matrix = B->matrix;
#endif

**Comment by jeanlucf22** [comment]
Some functionalities require a copy on the CPU. But when you use MAMGA, your data is typically allocated on the GPU and stays there.
Which function are you looking at?

**Comment by tokshgithub** [comment]
Some functionalities require a copy on the CPU. 
>> some or all?
>> i believe what you may be trying to do is
>> assign some value on the cpu and explicitly (via magma cuda wrapper)  move to gpu.
>> or  assign some value on the cpu and implicitly(via magma cuda unified memory wrapper) move it to gpu.

But when you use MAMGA, your data is typically allocated on the GPU and stays there.
>> ok!  

Which function are you looking at?

void TYPED_FUNC(
    bml_matrix2submatrix_ellpack) (
    const bml_matrix_ellpack_t * A,
    bml_matrix_dense_t * B,
    const int *core_halo_index,
    const int lsize)
{
    REAL_T *rvalue;

    int B_N = B->N;
#ifdef BML_USE_MAGMA
    REAL_T *B_matrix = bml_allocate_memory(sizeof(REAL_T) * B->N * B->N);
#else
    REAL_T *B_matrix = B->matrix;
#endif

**Comment by jeanlucf22** [comment]
This code is not using MAGMA at all. This is just there to enable the ellpack format to work properly with dense matrices allocated on the CPU when default dense matrices are on the GPU.

We really use MAGMA for the dense format in src/C-interface/dense

**Comment by jeanlucf22** [comment]
Note: if you wanted to do this operation directly on the GPU, you would need to write your own loop since MAGMA does not offer functionalities to do that. Unless you think this function is an important one and an efficient implementation is needed, I would leave it like that for now.

**Comment by tokshgithub** [comment]
there are performance advantage on the cpu to changing:

REAL_T *B_matrix = bml_allocate_memory(sizeof(REAL_T) * B->N * B->N);

to the following pair:
REAL_T *B_matrix = "bml_noinit_allocate_memory_align"(sizeof(REAL_T) * B->N * B->N);  (new function)
B_matrix = "bml_numa_init"(sizeof(REAL_T) * B->N * B->N); (new function)
and 
free_align(B_matrix);  (new function)

so i want to make sure that i can pair them correctly. so if this
REAL_T *B_matrix = bml_allocate_memory(sizeof(REAL_T) * B->N * B->N);
is used on the cpu, i can make the changes easily.

thanks

**Comment by jeanlucf22** [comment]
Even when building BML with MAGMA, bml_allocate_memory allocates memory on the CPU. GPU allocations happen specifically when creating matrices, and only there.

**Comment by tokshgithub** [comment]
ok! sounds good.

**Comment by jmohdyusof** [comment]
Hi Jean-Luc

Which branch is this in?

Also, I see you are using #ifdef for the MAGMA code sections; will there be a performance issue if this is changed to ‘if accel_type == magma’ for example?

Jamaludin Mohd Yusof, PhD
Future Architectures and Applications
CCS-7 Applied Computer Science Group
Phone: (505) 665-2870
Fax  : (505) 665-4939
Email: jamal@lanl.gov<mailto:jamal@lanl.gov>

On Feb 15, 2019, at 2:53 PM, Jean-Luc Fattebert <notifications@github.com<mailto:notifications@github.com>> wrote:


This code is not using MAGMA at all. This is just there to enable the ellpack format to work properly with dense matrices allocated on the CPU when default dense matrices are on the GPU.

We really use MAGMA for the dense format in src/C-interface/dense

**Comment by jeanlucf22** [comment]
This is now in the master branch. I don't think replacing the #ifdef with run time conditionals would slow down the code by any measurable amount, except maybe for very small matrices.

Jean-Luc
