### ISSUE TITLE
Use matching BML-API calls for Memory allocation.

### ISSUE THREAD

**Issue by tokshgithub** [lanl/bml#251]
Please kindly use matching bml api calls for memory "allocations" and "deallocations"
that is bml_memory_allocate(/**/) must be matched with

**Comment by nicolasbock** [comment]
Hi @tokshgithub , I don't quite understand what you are trying to say. Could you expand?

**Comment by tokshgithub** [comment]
ok, sounds good:

malloc()/calloc()/realloc() should not be used in the bml library except for within the allocate api.
the same goes for free().
bml_allocate_memory()/ bml_noinit_allocate_memory() should be matched with bml_free_memory().
Optimization work done in allocation api's will not be reflected when the above is not followed.

**Comment by nicolasbock** [comment]
Ah thanks, now I get it :smile: I completely agree with you.

Do you have particular places in mind where the above is not followed?

**Comment by tokshgithub** [comment]
Yes, feel free to grep for malloc and there are tons of them. sometimes malloc is paired with bml_free_memory().
So for example, undertake hood, if i implement an aligned malloc if a user frees it with free, they will get a segfault.

**Comment by nicolasbock** [comment]
Yes, I understand and agree with what you are saying. This should get fixed. If you have some spare cycles to take this on, I would like to encourage you to open a pull request.

Thanks for bringing this up!

**Comment by tokshgithub** [comment]
Yes, I understand and agree with what you are saying. This should get fixed. If you have some spare cycles to take this on, I would like to encourage you to open a pull request.
>> ok i will open a pull request.

Thanks for bringing this up!
>> your welcome

**Comment by nicolasbock** [comment]
Sorry, I didn't mean for you to close the issue. We can use it to track any PR against it. If you add a line such as

```
Issue: #251
```

To your commit message it will get linked automatically.
