### ISSUE TITLE
trace_mult-dense tests produce segfaults

### ISSUE THREAD

**Issue by mewall** [lanl/bml#318]
**Describe the bug**
The following produces a segfault in a magma 2.5.1 build:

build/tests/C-tests/bml-test -t dense -n trace_mult

The problem is in the below line of code. It looks like the code hasn't yet been magma-ified

Program received signal SIGSEGV, Segmentation fault.
bml_trace_mult_dense_single_real (A=<optimized out>, B=<optimized out>)
    at /lustre/scratch3/turquoise/mewall/CoPA/bml/src/C-interface/dense/bml_trace_dense_typed.c:118
118	        trace += A_matrix[i] * B_matrix[i];
Missing separate debuginfos, use: debuginfo-install blas-3.4.2-8.el7.x86_64 lapack-3.4.2-8.el7.x86_64 libgfortran-4.8.5-36.el7.x86_64
(gdb) list
113	  shared(A_localRowMin, A_localRowMax, myRank)  \
114	  reduction(+:trace)
115	    for (int i = A_localRowMin[myRank] * N; i < A_localRowMax[myRank] * N;
116	         i++)
117	    {
118	        trace += A_matrix[i] * B_matrix[i];
119	    }
120	
121	    return (double) REAL_PART(trace);
122	}

**Comment by nicolasbock** [comment]
@mewall Could you verify that @jeanlucf22 's PR fixes this issue? Thanks!

**Comment by jeanlucf22** [comment]
@mewall Is it still an issue?

**Comment by mewall** [comment]
This issue has been addressed.
