### ISSUE TITLE
indent script should work with older `emacs` versions

### ISSUE THREAD

**Issue by nicolasbock** [lanl/bml#327]
Currently the `indent.sh` script requires `emacs-26.2`. This should be relaxed so that older versions work with it as well.

**Comment by cnegre** [comment]
The same error happens in travis

+emacs26 --batch tests/Fortran-tests/trace_matrix_typed.F90 --eval '(setq f90-do-indent 2)' --eval '(setq f90-if-indent 2)' --eval '(setq f90-type-indent 2)' --eval '(indent-region (minibuffer-prompt-end) (point-max) nil)' -f save-buffer

Directory-local variables error: (wrong-type-argument symbolp (f90-if-indent . 2))

+for f in '"${FORTRAN_FILES[@]}"'
