### ISSUE TITLE
Add build scripts for early exascale architectures to the master branch

### ISSUE THREAD

**Issue by mewall** [lanl/bml#441]
**Describe the bug**
Work on builds for exascale architectures are not yet in the master branch, they are in the "tulip" and "jlse-intel" branches. Add build scripts to the master branch for these architectures and modify CMakelists.txt as needed to support these cases in a way that doesn't break other builds.

**Comment by jmohdyusof** [comment]
Based on the discussion this morning, I will register my suggestion of adding 'CPU_VENDOR' and 'GPU_VENDOR' (or 'ACC_VENDOR'?) as switches in the Cmake/build process.

**Comment by mewall** [comment]
Tulip build and install now works using the CMakelists.txt file in master. Tests are failing, however, with the below error. Forwarded to consultants for advice.

/data/jenkins_workspace/centos_pipeline_job_8.1_rel-3.9/rocm-rel-3.9/rocm-3.9-17-20201021/8.1/external/hip-on-vdi/rocclr/hip_global.cpp:69: guarantee(false && "Cannot find Symbol")

**Comment by mewall** [comment]
This issue will be addressed when PR #527 is merged into master
