### ISSUE TITLE
BML_OLD

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#443]
There is a BML_OLD flag in the main CMakeList.txt. Looks like it is obsolete. Can we get rid of it?

**Comment by jmohdyusof** [comment]
I have never used it, but it appears the 'src-old' directory it refers to no longer exists?

**Comment by nicolasbock** [comment]
I think so. It probably hasn't been used in ages 😄

**Comment by jmohdyusof** [comment]
Well at least it is well-named
