### ISSUE TITLE
git push failing

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#458]
I don't know if it is related to recent changes in the repo or not, but I cannot push anything anymore, not even to my own fork. I get error messages like:

To https://github.com/jeanlucf22/bml.git
 ! [remote rejected] distributed_trace -> distributed_trace (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/CI.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/jeanlucf22/bml.git'

Does anybody knows how to work around that issue?

**Comment by mewall** [comment]
Do we use codecov? I'm wondering if there is potentially any relation to the below message I received from NERSC...


Dear NERSC Users,


Codecov, a code coverage tool that many open-source projects use as part of their software testing processes, was recently compromised in a cyber attack.


This is a significant compromise that could impact the HPC user community. The attack enabled the malicious actors to exfiltrate data from users’ continuous integration (CI) environments, including sensitive data such as credentials, tokens, ssh keys, or API keys. The stolen data could be used by attackers to access any services, datastores, and application code and git repositories that could be accessed with these stolen credentials, tokens, or keys.


If you or your project uses Codecov, you should immediately expire/reset any tokens or keys used by Codecov, contained in your CI environment or git repository, or located in local source code. This includes tokens and keys used during CI from GitLab, GitHub, BitBucket, AWS, or any other service, as well as any credentials used as part of your continuous integration pipeline (e.g., database logins).


If you have any questions about actions you should take to protect your NERSC accounts and projects, please submit a ticket at https://help.nersc.gov<https://help.nersc.gov/>.

--
Rebecca Hartman-Baker, Ph.D
User Engagement Group Leader
National Energy Research Scientific Computing Center | Berkeley Lab
***@***.******@***.***> | phone: (510) 486-4810  fax: (510) 486-6459
Pronouns: she/her/hers

________________________________
From: Jean-Luc Fattebert ***@***.***>
Sent: Friday, April 23, 2021 1:15:01 PM
To: lanl/bml
Cc: Subscribed
Subject: [EXTERNAL] [lanl/bml] git push failing (#458)


I don't know if it is related to recent changes in the repo or not, but I cannot push anything anymore, not even to my own fork. I get error messages like:

To https://github.com/jeanlucf22/bml.git
! [remote rejected] distributed_trace -> distributed_trace (refusing to allow a Personal Access Token to create or update workflow .github/workflows/CI.yml without workflow scope)
error: failed to push some refs to 'https://github.com/jeanlucf22/bml.git'

Does anybody knows how to work around that issue?

**Comment by nicolasbock** [comment]
I split this into a separate issue @mewall to make discussions easier to follow. Please comment on the codecov issue in #459 .

**Comment by nicolasbock** [comment]
I am looking into it @jeanlucf22 .

**Comment by nicolasbock** [comment]
@jeanlucf22 I updated a few settings. Could you try this again and let me know whether things have improved? Thanks!

**Comment by jeanlucf22** [comment]
No, still not working...

**Comment by nicolasbock** [comment]
I am still not sure I understand the error message you are getting @jeanlucf22 . Could you create another branch and make a small change in the README and then push that to your fork? Please copy and paste the git output you are getting.

**Comment by jeanlucf22** [comment]
That works if I create another branch out of the master in https://github.com/jeanlucf22/bml.git which is not up to date. But that does not work if I use the latest master:

git clone https://github.com/jeanlucf22/bml.git
cd bml
git remote add upstream https://github.com/lanl/bml.git
git pull upstream master
git push origin master
Username for 'https://github.com': jeanlucf22
Password for 'https://jeanlucf22@github.com':
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/jeanlucf22/bml.git
 ! [remote rejected] master -> master (refusing to allow a Personal Access Token                                             
to create or update workflow `.github/workflows/CI.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/jeanlucf22/bml.git'

**Comment by jeanlucf22** [comment]
Maybe I should delete my fork and start from a new one?

**Comment by nicolasbock** [comment]
Yes, that might work. One theory I have is that `.github/workflows/CI.yml` differs between your fork and upstream. And that GitHub is not allowing you to modify the workflow because of a missing permission. If that's correct then a new fork would solve this problem. On the other hand it would mean that you won't ever be able to update the workflow, i.e. the tests we are running.

Since the whole issue is blocking you go ahead and try a new fork. I will have a look at user permissions to see if I can figure out how to solve this more properly.

**Comment by jeanlucf22** [comment]
That was my guess too. But I now cannot figure out how to delete my fork...

**Comment by nicolasbock** [comment]
This should be under "options" in your forked repository settings.

>

**Comment by jeanlucf22** [comment]
That seems to work now (just submitted a PR). But that is with a brand new fork...

**Comment by nicolasbock** [comment]
Could you create another branch in your brand new fork and modify the
CI.yml workflow file and submit that as a PR? If our theory was correct
then this should fail (unless that setting I just changed fixes it). I have
to admit that this is not a very carefully designed experiment :smile:

>

**Comment by jeanlucf22** [comment]
Just tried that. Still rejected.

**Comment by nicolasbock** [comment]
Ah I think I understand now. You are using `https` access to GitHub, not `ssh`. You had created a "personal access token" which are you using as your password.

GitHub recently added a "workflow" scope to tokens which I presume your token is lacking. Could you try this: Create a new personal access token and make sure the `workflow` scope is checked? And then try to push that PR again.

**Comment by jmohdyusof** [comment]
Possibly relevant, I received this message from another github repo: 

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

**Comment by nicolasbock** [comment]
This might be relevant if @jeanlucf22 was using a password instead of a personal access token. Using a password possibly does not have the necessary scope to make changes to workflows.

**Comment by jmohdyusof** [comment]
I meant it in the general sense of being aware that 'other' access methods might be being deprecated. I use SSH keys exclusively (apart from that one which I hadn't used for a while)..

**Comment by nicolasbock** [comment]
Yes, you are right. It definitely looks like GitHub is tightening their security stance. The new scope was added end of March of this year.

**Comment by jeanlucf22** [comment]
Yes, generating a new token with "workflow" selected works! (I can change the CI.yml)

I switched from password to tokens a few weeks ago because LLNL already requested some changes on github.com/llnl.
I tried to clone my repo with ssh yesterday, without success. So I am sticking with tokens for now.

**Comment by nicolasbock** [comment]
Nice! Tokens are completely fine to use.
