### ISSUE TITLE
Fortran and C tests should both allow to specify matrix size

### ISSUE THREAD

**Issue by nicolasbock** [lanl/bml#481]
I think we resolved this on the call: I will also note that it does appear that testf.F90 appears to hard-code N and M = 13, while bml_test.c allows N and M to be set from the command line. Should (can) these be made to both take the same arguments?

_Originally posted by @jmohdyusof in https://github.com/lanl/bml/discussions/480#discussioncomment-700887_

**Comment by jmohdyusof** [comment]
For reference, here are the options available for the C version: maybe it also makes sense to rename the fortran code bml_test.F90? 

    printf("Usage:\n");
    printf("\n");
    printf("-h | --help           This help\n");
    printf("-n | --testname TEST  Run test TEST\n");
    printf("-t | --type T         Choose the matrix type\n");
    printf("-p | --precision P    Choose matrix precision\n");
    printf("-l | --list           List all available tests\n");
    printf("-N | --N N            Test N x N matrices\n");
    printf("-M | --M M            Pass an extra parameter M to the test\n");

The fortran code only has:

  call get_arguments(test_name, matrix_type, element_type)

where element_type == precision
