### ISSUE TITLE
Version still set to 1.3.1

### ISSUE THREAD

**Issue by awvwgk** [lanl/bml#512]
**Describe the bug**
Building from release tag v2.0.0 still declares version 1.3.1 in build files.

https://github.com/lanl/bml/blob/190ee052638e9253f2627b03cd8732dcb5c583cb/CMakeLists.txt#L14-L18

**To Reproduce**
1. Get project source:
   `git clone https://github.com/lanl/bml && cd bml`
2. Checkout 2.0.0 release branch:
  `git checkout v2.0.0`
3. Setup new build:
  `cmake -B _build -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/_dist && ninja -C _build all install`
4. Check version:
  `PKG_CONFIG_PATH=$PWD/_dist/lib/pkgconfig pkg-config bml --modversion` shows 1.3.1

**Expected behavior**
Version should match with release.

**Additional context**
I try to package BML for conda-forge and stumbled upon the incorrect version number while checking the package integrity.

**Comment by nicolasbock** [comment]
Thanks a lot for raising this issue @awvwgk ! I have add pull request lanl/bml#513 to fix this.

**Comment by nicolasbock** [comment]
Since you are not tracking `master` but use the `v2.0.0` tag I presume that we also need to bump the library version so that you can package the library with correct version information. I'll open an issue for that as well.

Thanks again!

**Comment by awvwgk** [comment]
I'll package 1.3.1 for now and bump to 2.0.0 later once there is a clear recommendation from your side on how to patch the source.
