### ISSUE TITLE
Build failure on OSX

### ISSUE THREAD

**Issue by awvwgk** [lanl/bml#515]
**Describe the bug**

Building the Fortran bindings for BML 1.3.1 currently fails with a linking error on OSX due to unresolved symbols:

```
[  7%] Linking Fortran shared library libbml_fortran.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
  "_bml_add", referenced from:
      ___bml_add_m_MOD_add_two_deprecated in bml_add_m.F90.o
      ___bml_add_m_MOD_add_two in bml_add_m.F90.o
     (maybe you meant: ___bml_add_m_MOD_bml_add_norm, ___bml_add_m_MOD_add_identity_one , ___bml_add_m_MOD_bml_scale_add_identity , ___bml_add_m_MOD_add_two , ___bml_add_m_MOD_add_two_deprecated )
  "_bml_add_identity", referenced from:
      ___bml_add_m_MOD_add_identity_one in bml_add_m.F90.o
...
  "_bml_sum_squares_submatrix", referenced from:
      ___bml_norm_m_MOD_bml_sum_squares_submatrix in bml_norm_m.F90.o
     (maybe you meant: ___bml_norm_m_MOD_bml_sum_squares_submatrix)
  "_bml_threshold", referenced from:
      ___bml_threshold_m_MOD_bml_threshold in bml_threshold_m.F90.o
     (maybe you meant: ___bml_threshold_m_MOD_bml_threshold)
  "_bml_trace", referenced from:
      ___bml_trace_m_MOD_bml_trace in bml_trace_m.F90.o
     (maybe you meant: ___bml_trace_m_MOD_bml_trace, ___bml_trace_m_MOD_bml_tracemult )
  "_bml_traceMult", referenced from:
      ___bml_trace_m_MOD_bml_tracemult in bml_trace_m.F90.o
  "_bml_transpose_new", referenced from:
      ___bml_transpose_m_MOD_bml_transpose in bml_transpose_m.F90.o
  "_bml_transpose_triangle", referenced from:
      ___bml_transpose_triangle_m_MOD_bml_transpose_triangle in bml_transpose_triangle_m.F90.o
     (maybe you meant: ___bml_transpose_triangle_m_MOD_bml_transpose_triangle)
  "_bml_update_domain", referenced from:
      ___bml_allocate_m_MOD_bml_update_domain in bml_allocate_m.F90.o
     (maybe you meant: ___bml_allocate_m_MOD_bml_update_domain)
  "_bml_write_bml_matrix", referenced from:
      ___bml_utilities_m_MOD_bml_write_matrix in bml_utilities_m.F90.o
  "_bml_zero_matrix", referenced from:
      ___bml_allocate_m_MOD_bml_zero_matrix in bml_allocate_m.F90.o
     (maybe you meant: ___bml_allocate_m_MOD_bml_zero_matrix)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**To Reproduce**
Build with the conda-forge toolchain (GCC 9.3.0), see https://github.com/conda-forge/staged-recipes/pull/15582.
Build logs at Azure: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=349797&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310

**Expected behavior**
Should link correctly on OSX.

**Comment by nicolasbock** [comment]
Thanks for reporting this issue @awvwgk !

If I understand the CI output you link correctly then your commit https://github.com/conda-forge/staged-recipes/pull/15582/commits/3e924994f205fb50fd9a22b171e307524d44c27f fixed the OS X build. If that's the case, could you open a pull request with this change here? Please feel free to base this PR on the `v.1.3.1` tag if that's easier for your packaging.

**Comment by awvwgk** [comment]
> If I understand the CI output you link correctly then your commit https://github.com/conda-forge/staged-recipes/commit/3e924994f205fb50fd9a22b171e307524d44c27f fixed the OS X build.

I actually skipped the OSX build with that commit. The linked commit adds a patch to set the library directory in the `build.sh` script (related https://github.com/lanl/bml/issues/209) since the automatic choice is wrong for conda-forge's layout.

**Comment by nicolasbock** [comment]
How is the OS X build skipped though? Is [this line](https://github.com/conda-forge/staged-recipes/commit/3e924994f205fb50fd9a22b171e307524d44c27f#diff-40eb94663393d6ef57f4bec7bdc4a9e8e5b658e2ef81878d26858ec7e9355b8eR21) skipping the build?

Would your build pass if lanl/bml#518 was merged?

**Comment by awvwgk** [comment]
> How is the OS X build skipped though? Is [this line](https://github.com/conda-forge/staged-recipes/commit/3e924994f205fb50fd9a22b171e307524d44c27f#diff-40eb94663393d6ef57f4bec7bdc4a9e8e5b658e2ef81878d26858ec7e9355b8eR21) skipping the build?

The `build/skip` field in the recipe is used to disable platforms and/or architectures in conda-build. For now the BML recipe includes three Linux/x86_64 builds (serial, MPICH, OpenMPI) for version 1.3.1.

> Would your build pass if #518 was merged?

No, this fixes an installation issue on Linux where CMake installs the library into `$PREFIX/lib64` but conda-build expects it to be in `$PREFIX/lib`.

I didn't see any obvious pointers why the symbols are not found on OSX, but it seems like there is an issue with the name mangling between the Fortran / C interface. I don't have a Mac to debug this locally, but it might be straight-forward enough to create a CI job on GH actions runner to reproduce and debug this error (not convenient but possible).

I'm currently trying to figure out how straight-forward it is for me to use BML in my projects, therefore I'm packaging it for conda-forge to get an idea how easy it is to setup in practice.

**Comment by nicolasbock** [comment]
Thanks for the additional info. I'll have a look at setting up a OS X runner so we can test that regularly. What was the compiler setup you were using?

Please don't hesitate to use the [Disussions](https://github.com/lanl/bml/discussions) section here if you have any questions regarding the use of the library for your projects. We would be very interested in learning more about your application domain and your experience with the library (including performance).

**Comment by awvwgk** [comment]
This is the build environment used by conda-build, clang 11.1 and gfortran 9.3 were used:

```
    bzip2:                    1.0.8-h0d85af4_4          conda-forge
    c-ares:                   1.17.1-h0d85af4_1         conda-forge
    ca-certificates:          2021.5.30-h033912b_0      conda-forge
    cctools_osx-64:           949.0.1-h6407bdd_22       conda-forge
    clang:                    11.1.0-h694c41f_1         conda-forge
    clang-11:                 11.1.0-default_he082bbe_1 conda-forge
    clang_osx-64:             11.1.0-hb91bd55_2         conda-forge
    clangxx:                  11.1.0-default_he082bbe_1 conda-forge
    clangxx_osx-64:           11.1.0-h7e1b574_2         conda-forge
    cmake:                    3.20.5-hdbd2f3e_0         conda-forge
    compiler-rt:              11.1.0-h654b07c_0         conda-forge
    compiler-rt_osx-64:       11.1.0-h8c5fa43_0         conda-forge
    expat:                    2.4.1-he49afe7_0          conda-forge
    gfortran_impl_osx-64:     9.3.0-h9cc0e5e_22         conda-forge
    gfortran_osx-64:          9.3.0-h18f7dce_14         conda-forge
    gmp:                      6.2.1-h2e338ed_0          conda-forge
    isl:                      0.22.1-hb1e8313_2         conda-forge
    krb5:                     1.19.1-hcfbf3a7_0         conda-forge
    ld64_osx-64:              530-he8994da_21           conda-forge
    ldid:                     2.1.2-h7660a38_2          conda-forge
    libclang-cpp11.1:         11.1.0-default_he082bbe_1 conda-forge
    libcurl:                  7.77.0-hf45b732_0         conda-forge
    tk:                       8.6.10-h0419947_1         conda-forge
    xz:                       5.2.5-haf1e3a3_1          conda-forge
    zlib:                     1.2.11-h7795811_1010      conda-forge
    zstd:                     1.5.0-h582d3a0_0          conda-forge
```

**Comment by awvwgk** [comment]
@nicolasbock If you are interested just leave comment in https://github.com/conda-forge/staged-recipes/pull/15582 and I can add you as a recipe maintainer for BML at @conda-forge as well.

**Comment by nicolasbock** [comment]
Thanks @awvwgk .

**Comment by awvwgk** [comment]
I created a branch based on GCC 5 / GFortran 5 which is reproducing this error in GH actions (see https://github.com/awvwgk/bml/tree/osx)

You can inspect the logs of the run [here](https://github.com/awvwgk/bml/runs/3041557285?check_suite_focus=true).

**Comment by nicolasbock** [comment]
Thanks for adding lanl/bml#523! I'll have a closer look at the logs.

**Comment by awvwgk** [comment]
Unfortunately, cross-platform incompatibilities don't just go away after 90 days ;).
