### ISSUE TITLE
Inverse tests failure: error message on Spock

### ISSUE THREAD

**Issue by nicolasbock** [lanl/bml#541]
Here is the error message on Spock:

A*A^{-1}:
  48125112740076505563008870422958571520.000  0.045  0.091  0.128 -0.050 -0.054 -0.117  0.004  0.007 -0.076 -0.016 -0.058  0.056
  2228057713808967300907821900194906112.000  1.020  0.040  0.056 -0.022 -0.024 -0.051  0.002  0.003 -0.033 -0.007 -0.026  0.025
  831977549091652779792945609428697088.000  0.007  1.015  0.021 -0.008 -0.009 -0.019  0.001  0.001 -0.012 -0.003 -0.010  0.009
  2057876571466277674928940617400582144.000  0.018  0.037  1.052 -0.020 -0.022 -0.047  0.002  0.003 -0.031 -0.006 -0.024  0.023
  5385257365250968479796922994439225344.000  0.048  0.097  0.136  0.946 -0.057 -0.124  0.004  0.007 -0.081 -0.017 -0.062  0.060
  4431442827073042515916963091727777792.000  0.039  0.080  0.112 -0.044  0.953 -0.102  0.004  0.006 -0.066 -0.014 -0.051  0.049
  5423184837384496989375003605992472576.000  0.048  0.098  0.137 -0.054 -0.058  0.875  0.004  0.007 -0.081 -0.017 -0.062  0.060
  2983457520106945427992740385058193408.000  0.026  0.054  0.075 -0.030 -0.032 -0.069  1.002  0.004 -0.045 -0.009 -0.034  0.033
  2042563193759195635230185255591739392.000  0.018  0.037  0.052 -0.020 -0.022 -0.047  0.002  1.003 -0.031 -0.006 -0.023  0.023
  1362710292632419067556864294956040192.000  0.012  0.025  0.034 -0.014 -0.014 -0.031  0.001  0.002  0.980 -0.004 -0.016  0.015
  3654926655532787571990587711957237760.000  0.032  0.066  0.092 -0.036 -0.039 -0.084  0.003  0.005 -0.055  0.988 -0.042  0.041
  842216521446021217197509668306419712.000  0.007  0.015  0.021 -0.008 -0.009 -0.019  0.001  0.001 -0.013 -0.003  0.990  0.009
  5150532208034408268554085197064175616.000  0.046  0.093  0.130 -0.051 -0.055 -0.118  0.004  0.007 -0.077 -0.016 -0.059  1.057
[/autofs/nccs-svm1_home1/mewall/packages/bml/tests/C-tests/inverse_matrix_typed.c:49] Error in matrix inverse; ssum(A*A_inverse) = inf
Obtained 8 stack frames.
/autofs/nccs-svm1_home1/mewall/packages/bml/tests/C-tests/inverse_matrix_typed.c:50
/autofs/nccs-svm1_home1/mewall/packages/bml/tests/C-tests/inverse_matrix.c:16
/autofs/nccs-svm1_home1/mewall/packages/bml/tests/C-tests/bml_test.c:327
??:0
/home/abuild/rpmbuild/BUILD/glibc-2.26/csu/../sysdeps/x86_64/start.S:122
srun: error: spock16: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=283434.0

_Originally posted by @mewall in https://github.com/lanl/bml/issues/539#issuecomment-912831091_

**Comment by jeanlucf22** [comment]
@mewall could you share the build script you used on spock?

**Comment by mewall** [comment]
#!/bin/bash

module load PrgEnv-gnu
module load magma
module load cmake
module load openblas


rm -r build
rm -r install

MY_PATH=$(pwd)

export CC=${CC:=gcc}
export FC=${FC:=gfortran}
export CXX=${CXX:=g++}
export BLAS_VENDOR=${BLAS_VENDOR:=Auto}
export BML_OPENMP=${BML_OPENMP:=yes}
export INSTALL_DIR=${INSTALL_DIR:="${MY_PATH}/install"}
export BML_MAGMA=${BML_MAGMA:=yes}
export MAGMA_ROOT=${OLCF_MAGMA_ROOT}
export BML_TESTING=${BML_TESTING:=yes}
export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:=Release}
#export CMAKE_Fortran_FLAGS=${CMAKE_Fortran_FLAGS:="-O2 -ffree-form -ffree-line-length-200 -L${OLCF_OPENBLAS_ROOT}/lib -lopenblas"}
#export CMAKE_C_FLAGS=${CMAKE_C_FLAGS:="-O2 -I${HIP_PATH}/include -L${OLCF_OPENBLAS_ROOT}/lib -lopenblas"}
export CMAKE_Fortran_FLAGS=${CMAKE_Fortran_FLAGS:="-O0 -g -ffree-form -ffree-line-length-200 -L${OLCF_OPENBLAS_ROOT}/lib -lopenblas"}
export CMAKE_C_FLAGS=${CMAKE_C_FLAGS:="-O0 -g -I${HIP_PATH}/include -L${OLCF_OPENBLAS_ROOT}/lib -lopenblas"}
export EXTRA_LINK_FLAGS=${EXTRA_LINK_FLAGS:="-L${OLCF_OPENBLAS_ROOT}/lib -lopenblas"}

./build.sh configure

pushd build
make -j8
make install
popd


________________________________
From: Jean-Luc Fattebert ***@***.***>
Sent: Friday, September 3, 2021 7:18:32 PM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Inverse tests failure: error message on Spock (#541)


@mewall<https://github.com/mewall> could you share the build script you used on spock?

**Comment by jmohdyusof** [comment]
I think I suggested this before, is there any way to enable the Wiki on this repo so we can make e.g. 'Building on Spock' a permanently available topic? Other repos have the Wiki option...

**Comment by nicolasbock** [comment]
I enabled the wiki.
