### ISSUE TITLE
Inverse tests failure on Summit

### ISSUE THREAD

**Issue by mewall** [lanl/bml#542]
**Describe the bug**
Inverse tests fail when running "make test" on summit. However, individual tests pass.

**To Reproduce**
Build on summit with MAGMA using the build_olcf... script in the scripts/ dir

Load the modules at the top of the build script

Allocate a node interactively, eg

bsub -q batch -P csc304 -W 02:00 -nnodes 1 -Is $SHELL

cd build
make test

See the following:

Total Test time (real) = 655.08 sec

The following tests FAILED:
	237 - C-inverse-dense-single_real (Failed)
	238 - C-inverse-dense-double_real (Failed)
	239 - C-inverse-dense-single_complex (Failed)
	240 - C-inverse-dense-double_complex (Failed)
	241 - C-inverse-ellpack-single_real (Failed)
	242 - C-inverse-ellpack-double_real (Failed)
	243 - C-inverse-ellpack-single_complex (Failed)
	244 - C-inverse-ellpack-double_complex (Failed)
	245 - C-inverse-ellblock-single_real (Failed)
	246 - C-inverse-ellblock-double_real (Failed)
	247 - C-inverse-ellblock-single_complex (Failed)
	248 - C-inverse-ellblock-double_complex (Failed)
	249 - C-inverse-csr-single_real (Failed)
	250 - C-inverse-csr-double_real (Failed)
	251 - C-inverse-csr-single_complex (Failed)
	252 - C-inverse-csr-double_complex (Failed)

However, individual tests pass:
(base) bash-4.4$ jsrun --smpiargs="off" -a1 -n1 -g1 -c7 ./tests/C-tests/bml-test -n inverse -t dense -p single_real
.
.
.
 -0.000 -0.000  0.000  0.000  0.000  0.000  0.000 -0.000 -0.000 -0.000 -0.000  1.000 -0.000
 -0.000 -0.000 -0.000 -0.000 -0.000  0.000  0.000  0.000 -0.000 -0.000 -0.000  0.000  1.000
inverse matrix test passed

**Desktop (please complete the following information):**
 OLCF Summit

**Comment by nicolasbock** [comment]
Is there more output when the tests fail? Could you paste that for at least one failed test? Thanks!

**Comment by cnegre** [comment]
Could it be that also "make test" should be run as "jsrun .... make test"?

**Comment by mewall** [comment]
The individual tests all pass, so no...





________________________________
From: Nicolas Bock ***@***.***>
Sent: Tuesday, September 14, 2021 12:56:26 PM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Inverse tests failure on Summit (#542)


Is there more output when the tests fail? Could you paste that for at least one failed test? Thanks!

**Comment by mewall** [comment]
Using jsrun actually makes the job hang. I worked with consultants at OLCF on that issue and learned that jsrun is already invoked under the hood when running "make test" on summit.


I should be able to gather a bit more information about this issue later in the week (summit is down right now and I'm working to some FY end deadlines).

________________________________
From: Christian F. A. Negre ***@***.***>
Sent: Tuesday, September 14, 2021 1:13:10 PM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Inverse tests failure on Summit (#542)


Could it be that also "make test" should be run as "jsrun .... make test"?

**Comment by nicolasbock** [comment]
If you look at https://github.com/lanl/bml/runs/3073591941?check_suite_focus=true#step:4:8105 for example you see that a failed test produces some more output. You might have to scroll up quite a bit to see that though.

**Comment by mewall** [comment]
I can confirm that the inverse tests are now passing for recent crusher builds. I checked both the 'make test' result and ran individual dense tests to confirm. I would recommend doing the latter on summit, just in case.

________________________________
From: Jean-Luc Fattebert ***@***.***>
Sent: Thursday, February 3, 2022 8:48:43 AM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Inverse tests failure on Summit (#542)


It looks like these tests pass for me now on Summit. @mewall<https://github.com/mewall> can you confirm it is working for you now?

**Comment by jeanlucf22** [comment]
Issue #541 refers to the failure on Spock/AMD. Can we close that one then?
