### ISSUE TITLE
OpenMP offload assumes CUDA

### ISSUE THREAD

**Issue by mewall** [lanl/bml#547]
**Is your feature request related to a problem? Please describe.**
OpenMP offload assumes CUDA is being used in CMakeLists.txt

**Describe the solution you'd like**
Eliminate the assumption and ideally detect and use alternatives such as NVIDIA/CUDA vs AMD/HIP/rocm

**Comment by jmohdyusof** [comment]
I would like to expand this issue to include a thorough consideration of the flag logic and composability. For example, MKL_GPU is a separate flag that (implicitly) requires OMP_OFFLOAD to work but can function with OMP_OFFLOAD = false.

**Comment by mewall** [comment]
The title issue has been addressed. Will open a new issue for the expansion.
