### ISSUE TITLE
Finding BLAS with cmake

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#566]
The current build system needs some fixes when it comes to finding BLAS. Ultimately, it would be nice if cmake's FindBLAS would always work for us, but it is hard to guarantee. But as it if now, FindBLAS will not be reached if you specify a vendor not in the list for which we set flags specifically, such as OpenBLAS, which leads to an incorrect BLAS link.
Also: do we want to keep all the specific flags as given in CMakeList.txt as it is now? Or shall we let FindBLAS do it?

See cmake doc:
https://cmake.org/cmake/help/v3.10/module/FindBLAS.html

**Comment by nicolasbock** [comment]
I think this part of `CMakeList.txt` should definitely get a work over. When I wrote it the `FindBLAS` module was much less capable and we can very likely simplify a lot of the logic.

**Comment by jeanlucf22** [comment]
Resolved with PR #583
