### ISSUE TITLE
Build Failure on Virtual Machine

### ISSUE THREAD

**Issue by adarr567** [lanl/bml#568]
Build failed at 5%; I followed the LATTE-LAMMPS instructions to build bml to the letter (https://github.com/lanl/LATTE/wiki/Using-LATTE-through-LAMMPS#installing-the-libraries). Failed at the 'make' step. Build attempted on Ubuntu 20.04.3 LTS OS. I don't have much familiarity with Linux environments, so I'd really appreciate some help figuring out where I went wrong.

[CMakeError.log](https://github.com/lanl/bml/files/7847838/CMakeError.log)
[CMakeOutput.log](https://github.com/lanl/bml/files/7847839/CMakeOutput.log)

**Comment by nicolasbock** [comment]
Hi @adarr567

Did I understand you correctly that you ran https://github.com/lanl/bml/blob/master/scripts/example_build.sh to create the Makefile?

Also, could you add the output of the `make` command? If possible, re-run `make` as
```bash
make VERBOSE=1 2>&1 | tee make.output
```
And add `make.output` to this issue.

Thanks!

**Comment by adarr567** [comment]
Hi @nicolasbock, yes, your understanding is correct. Please find attached below make.output (given a different file extension to make nice with github).
[make.txt](https://github.com/lanl/bml/files/7849524/make.txt)
.

**Comment by nicolasbock** [comment]
Thanks @adarr567 

In the output file you'll find the actual error message:
```
In file included from /home/ptsg/bml/src/internal-blas/../C-interface/blas.h:4,
                 from /home/ptsg/bml/src/internal-blas/bml_gemm.c:3:
/usr/local/include/complex.h:10:1: error: unknown type name ‘using’
   10 | using namespace std;
      | ^~~~~
/usr/local/include/complex.h:10:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘std’
   10 | using namespace std;
      |                 ^~~
/usr/local/include/complex.h:13:10: fatal error: cmath: No such file or directory
   13 | #include <cmath>
      |          ^~~~~~~
compilation terminated.
```
which indicates that the included header file, `complex.h`, is using C++ syntax but the file `bml_gemm.c` was compiled using a C compiler. On my system `complex.h` does not contain the lines the compiler is complaining about. How did you install that header file? It is typically part of standard `glibc`.

**Comment by adarr567** [comment]
Hi @nicolasbock, I've only been working from the instructions in another set of documentation (https://github.com/lanl/LATTE/wiki/Using-LATTE-through-LAMMPS#installing-the-libraries) - sort of a "monkey see, monkey do" approach. Maybe some of the tools needed aren't installed correctly? Apologies for my inexpert responses, I'm a little out of my depth.

Presumably, I might have better results following the README for bml? It's possible the other documentation is simply out of date. In any case, that link will tell you all the commands I put into the terminal - in the meantime, I'll try to install using the documentation in this neck of the woods, and see if I have better outcomes.

**Comment by nicolasbock** [comment]
No worries @adarr567, there is nothing wrong with copy and paste :smile:

You said that you were building the library on Ubuntu 20.04 Focal. The correct `complex.h` should come from the `libc6-dev` package and is installed in `/usr/include/complex.h` and not `/usr/local/include/complex.h`.

In the title you mention a virtual machine. Could you give me some more details on what Focal is running on?

**Comment by adarr567** [comment]
Appreciate the understanding @nicolasbock! 

I am running VirtualBox in Windows 10 - actually, the machine image is from a particle-in-cell group (https://ptsg.egr.msu.edu/), so there might already be architecture in place. 

I looked, and complex.h is installed in both locations, and they do seem to be different.

**Comment by nicolasbock** [comment]
Is that image public so I can download it?

What code are you trying to build in the end? Is it LAMMPS with LATTE?

**Comment by adarr567** [comment]
Yep, here's the link which includes the image I used (https://ptsg.egr.msu.edu/pub/codes/VirtualMachines/20.04/).

I am trying to build LAMMPS with LATTE. Or rather, I have already built LAMMPS with LATTE successfully, and am now trying to include the BML and PROGRESS libraries.

**Comment by nicolasbock** [comment]
In the PTSG machine I did the following:

```bash
sudo apt install git cmake gfortran liblapack-dev
git clone https://github.com/lanl/bml.git
cd bml
EXTRA_CFLAGS="-nostdinc -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/include/x86_64-linux-gnu -I/usr/include" ./scripts/example_build.sh
make -C build
make -C build test
```

And everything works. Please note that the extra `CFLAGS` simply reiterate the default include paths without `/usr/local/include`:

```bash
$ cpp -v
Using built-in specs.
...
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/9/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

Please let us know if that fixes the issue.

**Comment by adarr567** [comment]
Aha! That fixed it, thank you for the assistance. Everything works now!

**Comment by nicolasbock** [comment]
Awesome! I'll close this issue then. Please open a new one in case you run into any other issues.
