### ISSUE TITLE
Explore transition to `C++` (using templates) with language bindings to `C`, `Fortran`, and `Python`

### ISSUE THREAD

**Issue by nicolasbock** [lanl/bml#570]
`C++` templates offer the potential to significantly reduce the number of lines of code. However, compiler name mangling might pose a challenge for language bindings to other languages.

- [ ] Write a small test library to explore this issue
- [ ] Support for multiple matrix formats
- [ ] Language bindings to `C`
- [ ] Language bindings to `Fortran`
- [ ] Language bindings to `Python`

**Comment by jmohdyusof** [comment]
In principle we could test C/Fortran interop with just the built-in C/Fortran tests? We should also confirm that this (name-mangling) is the only issue that concerned the team.

**Comment by nicolasbock** [comment]
It might help illustrate this idea and explore how the code would look like if we added a prototype implementation using `C++` with tests that use this prototype.

I don't think that data interoperability is an issue as long as we stick to the idea of passing "opaque" pointers around and access the matrix data only via library calls.

**Comment by nicolasbock** [comment]
Ok, thanks for the info. I will have a look there.
