### ISSUE TITLE
Do we still need support for the 'ellsort' format?

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#580]
When a developer adds a new functionality, they need to add it to all the formats. With the growing number of formats, it becomes quite a bit of work. Given that 'ellsort' is very similar to 'ellpack', it begs the question: do we still need to support 'ellsort'?

**Comment by nicolasbock** [comment]
I presume that the two formats do not exhibit a significant performance
difference. If that's the case then I am all for removing one of them.
