### ISSUE TITLE
Need linking with an offloaded distributed dense eigensolver

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#584]
The only distributed eigensolver we link with now is ScaLapack. We need to link with either ELPA or SLATE. SLATE may not be ready for production.

**Comment by mewall** [comment]
See the following issue with Frontier COE for some related information::

https://frontier-coe.atlassian.net/wiki/spaces/FCOE/pages/1494745089/Crusher+DSYEV

**Comment by jeanlucf22** [comment]
Working on ELPA coupling

**Comment by jeanlucf22** [comment]
Done in PR #665
