### ISSUE TITLE
IO and multiply-csr test failures on Summit

### ISSUE THREAD

**Issue by mewall** [lanl/bml#598]
**Describe the bug**
For a MAGMA+CUSOLVER build on Summit, the following tests fail:

96% tests passed, 33 tests failed out of 813

Total Test time (real) = 2040.98 sec

The following tests FAILED:
	273 - C-io_matrix-dense-single_real (Failed)
	274 - C-io_matrix-dense-double_real (Failed)
	275 - C-io_matrix-dense-single_complex (Failed)
	276 - C-io_matrix-dense-double_complex (Failed)
	277 - C-io_matrix-ellpack-single_real (Failed)
	278 - C-io_matrix-ellpack-double_real (Failed)
	279 - C-io_matrix-ellpack-single_complex (Failed)
	280 - C-io_matrix-ellpack-double_complex (Failed)
	281 - C-io_matrix-ellsort-single_real (Failed)
	282 - C-io_matrix-ellsort-double_real (Failed)
	283 - C-io_matrix-ellsort-single_complex (Failed)
	284 - C-io_matrix-ellsort-double_complex (Failed)
	285 - C-io_matrix-ellblock-single_real (Failed)
	286 - C-io_matrix-ellblock-double_real (Failed)
	287 - C-io_matrix-ellblock-single_complex (Failed)
	288 - C-io_matrix-ellblock-double_complex (Failed)
	289 - C-io_matrix-csr-single_real (Failed)
	290 - C-io_matrix-csr-double_real (Failed)
	291 - C-io_matrix-csr-single_complex (Failed)
	292 - C-io_matrix-csr-double_complex (Failed)
	309 - C-multiply-csr-single_real (Failed)
	734 - fortran-io-dense-single_real (Failed)
	735 - fortran-io-dense-double_real (Failed)
	736 - fortran-io-dense-single_complex (Failed)
	737 - fortran-io-dense-double_complex (Failed)
	738 - fortran-io-ellpack-single_real (Failed)
	739 - fortran-io-ellpack-double_real (Failed)
	740 - fortran-io-ellpack-single_complex (Failed)
	741 - fortran-io-ellpack-double_complex (Failed)
	742 - fortran-io-ellsort-single_real (Failed)
	743 - fortran-io-ellsort-double_real (Failed)
	744 - fortran-io-ellsort-single_complex (Failed)
	745 - fortran-io-ellsort-double_complex (Failed)

**To Reproduce**

cd bml
BLAS_VENDOR=OpenBLAS BML_CUSOLVER=yes bash scripts/build_olcf_summit_gnu_mgma_openblas.sh
module load cmake
module load cuda
module load gcc/9.3.0
module load netlib-lapack
module load openblas
module load magma
bsub -Is -W 2:00 -nnodes 1 -P $ACCOUNT $SHELL
cd build
make test

**Comment by jeanlucf22** [comment]
@mewall Are you running on /gpfs? What is the error message?

**Comment by mewall** [comment]
(base) bash-4.4$ jsrun -n1 -a1 -g1 -c7 --smpiargs=off tests/C-tests/bml-test -n io_matrix -t dense -p single_real
io_matrix
N = 13
ERROR:  One or more process (first noticed rank 0) terminated with signal 11
(base) bash-4.4$ pwd
/ccs/home/mewall/packages/test/bml/build

**Comment by jeanlucf22** [comment]
IO are restricted in your home directory on Summit. Go on /gpfs
