### ISSUE TITLE
BML matrices data members domain and domain2

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#599]
In the multiplication function distributed2d format, I create 4 extra matrices for store copies of data belonging to other MPI tasks. In my performance analysis, I noticed that these matrix creations leads to some non-negligible overhead. The overhead comes mostly from calling bml_default_domain() twice every time you create a matrix, which each leads to 6 memory allocations. That code could be optimized and that overhead largely reduce. But I was wondering first if we actually need all these data members, in particular domain2. To me, it looks like the only functions using domain2 are never used internally, and never tested. But some of these functions  --- like bml_save_domain() --- are used in PROGRESS, although none of these seem to be called by any test either.

Questions:
1) do we need to keep domain2?
2) if we do, how do we make sure we don't break its usage since we have no tests for it?

**Comment by jeanlucf22** [comment]
@cnegre This is one issue I was mentioning to you today. Any thoughts about that?

**Comment by cnegre** [comment]
That is currently used by some of the routines we want to replace in
progress. Let's keep it for now.
