### ISSUE TITLE
GPU offload language

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#603]
Right now, if the build script specifies:
export BML_OMP_OFFLOAD=${BML_OMP_OFFLOAD:=yes}
cmake looks for CUDA, which is specific to NVIDIA and to offloading

Jamal was suggesting today to use a flag like DEV_ARCH which would specify the architecture. Using that, for NVIDIA, we would look for CUDA, for AMD, we would look for HIP,...

**Comment by jmohdyusof** [comment]
Related question; is there a way to have Cmake handle the compiler-specific flags for OMP offload, which are now explicitly specified as CFLAGS?
