### ISSUE TITLE
Add hip dependency to bml cmake package 

### ISSUE THREAD

**Issue by mewall** [lanl/bml#608]
**Describe the bug**
When running PROGRESS cmake building against BML with MAGMA and HIP on Crusher, error messages like the following occur:

CMake Error at src/CMakeLists.txt:3 (add_library):
  Target "progress" links to target "hip::host" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

It's necessary to add find_package(hip) to the PROGRESS CMakeLists.txt file in this case. 

It would be good to install the BML cmake package with the necessary hip dependencies, if possible.

**To Reproduce**
On crusher
cd bml
source scripts/setenv_crusher_magma_gcc.sh
module swap rocm rocm/5.1.0
bash scripts/build_crusher_magma_gcc.sh
cd ../qmd-progress
bash scripts/build_crusher_magma_gcc.sh

**Comment by jeanlucf22** [comment]
@mewall still an issue?

**Comment by mewall** [comment]
Yeah, still an issue.

It would be nice not to have to find_package(hip) when building progress...

**Comment by mewall** [comment]
Addressed in PR #683
