### ISSUE TITLE
OpenMP offload syntax

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#612]
https://github.com/lanl/bml/blob/4d5ee4603f003178589710c6e257a0e9ef56d276/src/C-interface/ellpack/bml_element_multiply_ellpack_typed.c#L87

@jmohdyusof Is it correct OpenMP offload syntax? These arrays are not allocated on GPU before that mapping... I see warnings that may be related to that:
"Encountered a zero-length array section that points to memory starting at address 0x2c896940. Because this memory is not currently mapped on the target device 0, a NULL pointer will be passed to the device."

**Comment by mewall** [comment]
@jeanlucf22 The syntax is correct according to the spec (but I'd be OK adding an alloc clause above to improve readability). See https://www.openmp.org/spec-html/5.0/openmpsu109.html#x142-6190002.19.7.1

If the map clause appears on a target, target data, or target enter data construct then on entry to the region the following sequence of steps occurs as if performed as a single atomic operation:

1.
    If a corresponding list item of the original list item is not present in the device data environment, then:

    a)
        A new list item with language-specific attributes is derived from the original list item and created in the device data environment; 
    b)
        The new list item becomes the corresponding list item of the original list item in the device data environment; 
    c)
        The corresponding list item has a reference count that is initialized to zero; and 
    d)
        The value of the corresponding list item is undefined;

**Comment by mewall** [comment]
@jeanlucf22 Or maybe item d) means that the array values are not passed? In which case the syntax isn't correct...this might be a bug, at least in some compilers.

**Comment by jmohdyusof** [comment]
Sorry if I missed this originally. The alloc clause only allocates but does not pass the values. I use 'alloc' followed by 'update:to'.
