### ISSUE TITLE
build.sh error: ./build.sh: line 194: BML_CUSPARSE: unbound variable

### ISSUE THREAD

**Issue by finkeljos** [lanl/bml#634]
I just cloned a new copy of the master branch and obtained the following error when executing ./build.sh on Darwin:

./build.sh: line 194: BML_CUSPARSE: unbound variable

**Comment by nicolasbock** [comment]
Could you list the environment variables you were using?

**Comment by finkeljos** [comment]
I did notice a recent change on 6/21 involving CUSPARSE but could be that the env was messed up somehow. I just re-did it and built bml without this CUSPARSE problem.
