### ISSUE TITLE
cannot compile dummy code with newly cloned master branch build

### ISSUE THREAD

**Issue by finkeljos** [lanl/bml#635]
**Describe the bug**
Built a dummy "hello world" .cc code that links only with bml build obtained from new master clone and I obtain the following compilation error for the dummy code:

In file included from /tmp/bml/install/include/bml.h:201,
                 from main.cc:1:
/tmp/bml/install/include/bml_elemental.h:18:15: error: expected initializer before ‘bml_get_element_single_complex’
   18 | float complex bml_get_element_single_complex(
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/bml/install/include/bml_elemental.h:23:16: error: expected initializer before ‘bml_get_element_double_complex’
   23 | double complex bml_get_element_double_complex(
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

using the modules:  

1) cuda/11.4.2   2) gcc/9.4.0   3) openmpi/3.1.6-gcc_9.4.0   4) cmake/3.22.2

**To Reproduce**
1. Clone bml master branch.   
2. Build bml using scripts/example_build.sh
3. cd build; make -j; make install
4. compile dummy code with bml

compile command: 

gcc -I/tmp/bml/install/include main.cc -o main -L/tmp/bml/install/lib64 -lbml

dummy code:  main.cc

  #include "bml.h"
   
   int
   main ()
   {
     printf("BONJOUR MONDE");
     return 0;
   }

**Comment by mewall** [comment]
Can you try naming the code main.c? I know you're using gcc, but seems like the compiler might be treating the source as if it were C++ code.

**Comment by finkeljos** [comment]
That worked, thanks!

I don't understand why bml would complain though...
