### ISSUE TITLE
Getting message "I shouldn't be here on all runs!"

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#637]
https://github.com/lanl/bml/blob/22e06a5bfce8c9fbd7ddd67ac2fdf596848c6cbc/src/C-interface/dense/bml_add_dense_typed.c#L141

Getting this message when running using dense format. Runs are executed correctly, however there is no way to turn 
off the message!

Compiled with GNU and  MKL libs

**Comment by jmohdyusof** [comment]
Someone with permissions just remove the line. I cannot even tell what the endif following that printout belongs to.
