### ISSUE TITLE
cuSparse uses a lot of memory

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#652]
It looks like the cuSparse function to multiply two sparse matrices uses a lot of memory, preventing benchmarking on matrices larger than 2000x2000. Let's try to figure out how much memory exactly and report to NVIDIA if excessively high.

**Comment by mnicely** [comment]
Are you trying to use SpGEMM?

**Comment by oseikuffuor1** [comment]
@mnicely, yes that is correct. We are using SpGEMM to multiply two sparse matrices.

**Comment by jeanlucf22** [comment]
@oseikuffuor1 Could you please update this issue here with current status and timeline for action? Thanks.
