### ISSUE TITLE
Using rocsparse for addition on AMD GPU

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#653]
Profiles have shown that the addition takes a substantial amount of time compared to the rest when multiplications are handled by rocsparse. Let's try to use rocsparse addition too to improve performance.

**Comment by jeanlucf22** [comment]
@mewall is it still in progress, or is it done?

**Comment by mewall** [comment]
> @mewall is it still in progress, or is it done?

Still in progress
