### ISSUE TITLE
cmake search for 'fabs' 

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#660]
When building BML, we require cmake to find the functions 'fabs' in the math library typically specified by '-lm'. Is 'fabs' always in that library? I seem to have found a case where it is not. Do we need to keep that check? This is just a check and nothing is set when 'fabs' is found. See CMakeList.txt in main directory.

**Comment by nicolasbock** [comment]
If I remember correctly the reason for this change was that when compiling
with gcc/MKL the linker did not automatically include a `-lm` and the math
functions where missing. I can't quite remember why I added this test for
`fabs()` when I also added the `-lm` part to the linker anyway :smile:.

I don't think linking unconditionally to `libm` is bad even if it wasn't
needed on some machines. In other words, I think it is safe to remove this
`fabs()` check.

**Comment by jmohdyusof** [comment]
If -lm doesn't always get fabs, does it get included somewhere else? We use it for all the thresholding functions.

**Comment by nicolasbock** [comment]
It should be included with either blas or lapack. Currently it might be be twice in the linker line.

**Comment by jeanlucf22** [comment]
Looks like gcc may inline that function
https://stackoverflow.com/questions/46400205/why-fabs-doesnt-require-the-lm-option-when-compiling-with-gcc
