### ISSUE TITLE
Fix abs value compiler warnings

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#668]
Also, building master I see errors like:
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:31:28: warning: using floating point absolute value function 'fabs' when argument is of complex type [-Wabsolute-value]
            C[i * N + j] = fabs(val) > threshold ? val : 0.;
                           ^
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:31:28: note: use function 'cabsf' instead
            C[i * N + j] = fabs(val) > threshold ? val : 0.;
                           ^~~~
                           cabsf
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:54:30: warning: floating-point comparison is always true; constant cannot be represented exactly in type 'float' [-Wliteral-range]
        if (ABS(A[i] - B[i]) > ABS_TOL)

_Originally posted by @jmohdyusof in https://github.com/lanl/bml/issues/663#issuecomment-1314271162_

**Comment by jmohdyusof** [comment]
I think the warning: floating-point comparison is always true; constant cannot be represented exactly in type 'float' is potentially important

**Comment by jeanlucf22** [comment]
Fixed in PR #669
