### ISSUE TITLE
Testing third party libraries

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#681]
We sometimes encounter failures due to problems in third-party libraries (not compiled properly, out of date,...). Tracking down these issues can take a lot of time.

To improve the situation, it would be nice to have some extras tests that test these third party libraries upfront and report issues right away, including performance issues.

**Comment by nicolasbock** [comment]
Let's start by compiling a list of those third-party libraries. That would make it easier to design and implement tests.

**Comment by jeanlucf22** [comment]
I would start with MAGMA, which has already caused us some trouble...

**Comment by nicolasbock** [comment]
Does the test pipeline you run via GitLab have access to GPUs? If it does then we could add tests that are run only there and not on GitHub.

**Comment by jeanlucf22** [comment]
Yes, it does run GPU.
BTW, we already have one test like that for OpenMP offload: 
https://github.com/lanl/bml/blob/0619203a8f63895e0719cb9d293273a5bcef2624/tests/C-tests/CMakeLists.txt#L3

**Comment by nicolasbock** [comment]
Do you then basically just have to run a test in GitLab with OMP offload enabled?

**Comment by jeanlucf22** [comment]
All it does it run an extra test when BML_OMP_OFFLOAD=1 (on gitlab or not). This test is checking that compiler is actually offloading to GPU.
In the same way, we could have a test for MAGMA when MAGMA is ON.

**Comment by jeanlucf22** [comment]
PR #741 is the fist step with magma.
