### ISSUE TITLE
Fortran interface to bml_print_version

### ISSUE THREAD

**Issue by jeanlucf22** [lanl/bml#692]
How do we generate a Fortran interface for this function?
https://github.com/lanl/bml/blob/d15a9f340e077ffd13a7a6197e5bf62256d9c7dc/src/C-interface/bml_logger.c#L173
I don't know if it is safe/possible to pass a file reference between Fortran and C...
Or do we need to "replicate" it in Fortran?

**Comment by nicolasbock** [comment]
I doubt passing a file descriptor between Fortran and C would be portable, see https://fortran-lang.discourse.group/t/c-file-pointers-and-fortran-file-units/4159.

But is passing such a descriptor necessary? For example, you could remove the `FILE *` argument from the C function and have it print to `stdout` always. Then it's not necessary to pass anything between Fortran and C.

In other words, is there a use case in which you would want to print this information into anything else but `stdout`?

**Comment by jeanlucf22** [comment]
Agree. I had been reading similar things about this issue. Hardcoding stdout is probably a good option.
