### ISSUE TITLE
Enable precision consistent calculations

### ISSUE THREAD

**Issue by aradi** [lanl/bml#7]
Routines which use additional to the bml-matrix also floating point input (e.g. the prefactor in `bml_scale()`) do not work from Fortran if the floating point input has single precision. Consequently, it is not possible to use the library from a Fortran code, which consistently uses only single point numbers. (See example below.)

```
program test
  use bml

  ! Working precision = single precision
  integer, parameter :: wp = kind(1.0e0)
  integer, parameter :: NN = 3
  type(bml_matrix_t) :: aa
  real(wp) :: prefac

  call bml_random_matrix(BML_MATRIX_DENSE, BML_PRECISION_SINGLE_REAL, NN, NN, &
      & aa)
  prefac = 2.0_wp
  call bml_scale(prefac, aa)   ! Fails to compile

end program test
```

In order to fix this, one would need to have accordingly typed routines in the C-API, which can then be wrapped in Fortran.

**Comment by nicolasbock** [comment]
Would you want complex scalar parameters as well, or are you thinking of single/double reals only?

**Comment by aradi** [comment]
Good point! I think, most important is to have single/double real first, enabling you to do arithmetic with consistent precision with the current functionality of the library. Later, if the library is extended to enable scaling with complex numbers as well, then that would need also both precisions again.

**Comment by nicolasbock** [comment]
That sounds good. For now we'll allow single/double scalars.

**Comment by nicolasbock** [comment]
We are moving on this issue again: We committed b93a366260afdd0ac0b0be4a5970e51173c9b7ed to change the `bml_scale` functions.
