### ISSUE TITLE
work undeclared

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#703]
**Describe the bug**
Code not compiling 

Using the following variables:
MY_PATH=$(pwd)
export CC=${CC:=gcc}
export FC=${FC:=gfortran}
export CXX=${CXX:=g++}
export BML_INTERNAL_BLAS=${BML_INTERNAL_BLAS:=yes}
export BLAS_VENDOR=${BLAS_VENDOR:=None}
export BML_OPENMP=${BML_OPENMP:=yes}
export INSTALL_DIR=${INSTALL_DIR:="${MY_PATH}/bml/install"}
export BML_TESTING=${BML_TESTING:=no}
export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:=Release}

**Screenshots**

/home/cnegre/LCC1/bml/src/C-interface/dense/bml_diagonalize_dense.c: In function ‘bml_diagonalize_dense_single_real’:
/home/cnegre/LCC1/bml/src/C-interface/dense/bml_diagonalize_dense.c:143:10: error: ‘work’ undeclared (first use in this function)
  143 |     free(work);
      |          ^~~~
/home/cnegre/LCC1/bml/src/C-interface/dense/bml_diagonalize_dense.c:143:10: note: each undeclared identifier is reported only once for each function it appears in
/home/cnegre/LCC1/bml/src/C-interface/dense/bml_diagonalize_dense.c: In function ‘bml_diagonalize_dense_double_real’:
/home/cnegre/LCC1/bml/src/C-interface/dense/bml_diagonalize_dense.c:360:10: error: ‘work’ undeclared (first use in this function)
  360 |     free(work);

**Comment by nicolasbock** [comment]
The code is building for me @cnegre . Did https://github.com/lanl/bml/pull/704 address this issue?
