### ISSUE TITLE
Rename f_c_string function

### ISSUE THREAD

**Issue by jmohdyusof** [lanl/bml#744]
Intel has informed us future compilers will have built-in f_c_string which will conflict with that defined in BML:

"Iso_c_binding, for fortran 2023 contains the new intrinsic f_c_string.  In bml/src/Fortran-interface/bml_fc_tools_m.F90, they have their own f_c_string function.  Because in bml_c_interface_m.F90, they include all of iso_c_binding, the new function comes into play, causing problems.  This will cause problems for 2023 compliant compilers."

Since f_c_function is only used in bml_utilties_m.F90 I propose renaming our version bml_f_c_string to avoid issues. I can do it myself if approved.

**Comment by jeanlucf22** [comment]
I agree with your proposal.
