### ISSUE TITLE
Non blas/lapack versions of the routines

### ISSUE THREAD

**Issue by cnegre** [lanl/bml#76]
It would be good to have a non-blas/lapack version of the routines such as bml_multiply. This will 
help us debugging and do special compilations for trying new architectures ...  This could be selected at compiling time with BLAS_VENDOR="NONE" or something similar.

**Comment by nicolasbock** [comment]
Nice idea!

**Comment by suemni** [comment]
?This will be useful when working with new architectures that may not have matrix libs.


________________________________

**Comment by nicolasbock** [comment]
I start with multiply and add hand written `?gemm` functions that will get built if `BLAS_VENDOR=NONE`.
